### ISSUE TITLE
Final Test Bugs: Startpassage in lower case

### ISSUE THREAD

**Issue by manuelpolzhofer** [TweeZcodeCompiler/twee_zcode_compiler#109]
if the start passage name is written in lowercase:

::start
Hello World

the error message from the compiler could be improved.

instead of "no Start passage" maybe automatically lowercase all passage names before searching startpassage name

**Comment by manuelpolzhofer** [comment]
issue was mentioned in Till feedback email as well

**Comment by lyrkiir** [comment]
The Start passage needs to be in the format of "Start" otherwise the twee compiler won't recognize it

**Comment by manuelpolzhofer** [comment]
ah okay. then maybe a more specific error mesage. but anyway the priority of this bug is really low

**Comment by lyrkiir** [comment]
fixed in fixIssues108109
