### ISSUE TITLE
Final Test Bugs: frotz error after starting program

### ISSUE THREAD

**Issue by manuelpolzhofer** [TweeZcodeCompiler/twee_zcode_compiler#112]
possible to compile but error after starting program in frotz
twee file works fine in twine.

t15.twee
::Start
Hello World
[[Moon]]

::Moon
I am the moon

::Venus
I am Venus

::Mars
I am Mars
::Mars1
I am Mars
::Mars2
I am Mars
::Mars3
I am Mars
::Mars4
I am Mars
::Mars5
I am Mars
::Mars6
I am Mars
::Mars7
I am Mars
::Mars8
I am Mars
::Mars9
I am Mars

**Comment by lyrkiir** [comment]
file does compile and run without error in frotz as of commit 5cbe0744e4c797538b0b414a121ae467e43507f5
